spring.application.name=crypto-interpreter

# Server
server.port=8080

# DataSource - PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://pg-3444024-gabrielanthony540-9a36.a.aivencloud.com:15203/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS__oT8Pi3ER36ni8zPnrd


# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# // api brapi dev
brapi.api.token=rebmE8FRzWZWLNGPtuSSdo
